### ISSUE TITLE
Fixing the blog theme

### ISSUE THREAD

**Issue by BoPeng** [vatlab/blog#1]
I have

1. Set up hugo. My local hugo was at version 0.16 and I had to upgrade it to version 0.31.
2. Get [hugo-bootstrap-premium](https://themes.gohugo.io/hugo-bootstrap-premium/). 
3. Create a post with `hugo new post/sos-notebook.md`
4. Set publish directory of the `blog` repo to `docs`. Set `publishDIr="docs"` in [`config.toml`](https://github.com/vatlab/blog/blob/master/config.toml) to match github repo so that the HUGO-generated static site will be displayed
5. Run `hugo` to generate static site under `docs`
6. `git add`, `git commit` and `git push` to publish docs.

The blog is running but it is a total mess right now and we need to fix a lot of things.

**Comment by gaow** [comment]
Apparently it did not load any of the CSS file. I'm a bit puzzled: doesn't it work when strictly following these instructions?

https://github.com/appernetic/hugo-bootstrap-premium

**Comment by BoPeng** [comment]
To make things easier, I cloned the modified theme (with comments from github) from donw.io but the css still does not work. Should be some simple configuration problem.

**Comment by gaow** [comment]
Ha that's classic -- check the website now. I changed base URL `http://` to `https://`. I guess you can switch that other theme back and see?

**Comment by gaow** [comment]
BTW as shown on the `hugo-bootstrap-premium` theme template repo, the base URL is best set to `/`

**Comment by BoPeng** [comment]
Great, your commit fixes the problem! Now the comment points to the donw.io, which should be easy to fix.

**Comment by BoPeng** [comment]
Good, the comment system is working now. The theme actually does not look too bad so we will just need some small tweaks.

**Comment by gaow** [comment]
>  The theme actually does not look too bad so we will just need some small tweaks.

Are you sure about that? I think the mainstream is no longer dark themed website, and dark themes always hurts my eyes ... I like your [initial pick better](https://raw.githubusercontent.com/appernetic/hugo-bootstrap-premium/master/images/screenshot2.png). But this is all very subjective. So maybe @Qwertyuiop21672 's vote will be important :)

**Comment by gaow** [comment]
Okey my test comment was displayed yet apparently it does not allow for emojis. I guess now you can test deleting my comment :)

**Comment by BoPeng** [comment]
The initial one asks me to write pages such as about, dashboard, and disclaimer, and I will have to modify the templates to port the comment system over. It is not that difficult but I apparently do not have time for it. I think I will add that theme back, ask @Qwertyuiop21672 to tweak it, and switch to it when it is ready.

In the meantime we can work on the hackernews post. I changed our pictures to dynamic ones ([gif](https://vatlab.github.io/sos-docs/)), which should help explain the ideas if we add them to the post.

**Comment by BoPeng** [comment]
Just removed yours but I think emojis should work after we add appropriate css/js header. I like the fact that I can add/remove/modify comments freely from the ticket tracker. What a genius idea.

**Comment by BoPeng** [comment]
It could be good enough to copy the theme color and fonts from the bootstrap theme if the overall style is acceptable. Personally I think it would be an overkill to have a top banner with dedicated about page etc, although I can link the about page to my MD Anderson profile.

**Comment by gaow** [comment]
Agreed -- I too appreciate the simplicity of the current theme. I am only anti-darkness :)

**Comment by gaow** [comment]
I checked the theme code with developer tools on google chrome. Here are a few things that needs to be fixed:

![2017-11-29-21-07-21_scrot](https://user-images.githubusercontent.com/917985/33411121-63cf9f02-d549-11e7-8310-eee06c2cfbb7.png)

**Comment by BoPeng** [comment]
I tried to use bootstrap themes for the blueberry theme but failed because it is a completely customized theme that uses classes that are not bootstrap. I tried to use the bootstrap theme but it requires too much customization to get a working header bar. So I now switched to a really simple theme called [kiss](https://themes.gohugo.io/kiss/). It is perhaps not as nice as the previous two but it does not have dark background and requires less customization....

**Comment by gaow** [comment]
I think KISS is nice! Only thing I miss about the blueberry theme is the home page that had center-aligned text with a large blog title and your affiliations but I assume those are easy to add in, at least by directly changing the HTML template.

**Comment by BoPeng** [comment]
The comment system works now, but some css is needed to properly space the comments and button. Enough for today though.

I have added a button to link the blog from the sos homepage.

**Comment by gaow** [comment]
>  but some css is needed to properly space the comments and button. 

I moved that css from the dark theme -- check [the code](https://github.com/vatlab/blog/blob/master/themes/kiss/static/css/custom.css) and the HTML output on your post. Maybe you want to change the colors? 

Also this script still has issues:

![2017-11-30-00-48-21_scrot](https://user-images.githubusercontent.com/917985/33417813-9659075a-d568-11e7-834f-d9a6de80d7b7.png)

**Comment by BoPeng** [comment]
The dark theme does not work well here. Let me try.

**Comment by BoPeng** [comment]
Should be ok now. I also added a "category" property for the posts to display `vatlab > SoS Notebook`.

**Comment by BoPeng** [comment]
@Qwertyuiop21672 Right now the category label shares the same `<a>` with the main title. It would be better to make the `<a>` only applicable `vatlab`, and allows the subcategory to link to its own stuff (e.g. link `SoS` to SoS homepage). The per-category link can be specified in the post but we will need to first adjust the title payout in [`nav.html`](https://github.com/vatlab/blog/blob/master/themes/kiss/layouts/partials/nav.html#L5)
 
![image](https://user-images.githubusercontent.com/9889312/33455148-ca605922-d5e0-11e7-9df8-a2216c10ab69.png)
