### ISSUE TITLE
Blog post shows not available for comment for unknown reason

### ISSUE THREAD

**Issue by BoPeng** [vatlab/blog#3]
I have seen this from time to time and have not figured out why this happens:

![image](https://user-images.githubusercontent.com/9889312/33456365-d0a0334e-d5e4-11e7-8359-5a38f64c6292.png)

@gaow what do you see over there now?

**Comment by gaow** [comment]
Looks fine on my end. Maybe the API does not like your IP?

**Comment by BoPeng** [comment]
It is working now. According to the [source code](https://github.com/vatlab/blog/blob/master/themes/kiss/static/js/github-comments.js#L83), the error message is displayed when an AJAX call fails, so it might be something related to network or github API.

**Comment by BoPeng** [comment]
Found the reason:

```
{
  "message": "API rate limit exceeded for 143.111.84.121. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by gaow** [comment]
Okey does your fix distinguish the case when wrong / non-existing URL is given so that no valid information can be extracted? I was thinking the prompt should depend on the exact error message you receive.

**Comment by BoPeng** [comment]
It is up to us to ensure there is a ticket open for all blog posts. Then whatever error happens, the new error message provides a way to access related issue directly. The exact error message does not really matter and I was even considering replacing the hard-to-understand "rate limit" explanation with something like "Ohh, github hiccuped, ....".

**Comment by BoPeng** [comment]
At least the reason is now known.
